In [32]:
import numpy as np
a=np.array([10,20,30,40,50,60])
print(a)
print(type(a))

# matrix in numpy
b=np.array([[1,2,3],[5,6,7],[8,9,6]])
print(b)

#  slicing in numpy
print(a[0:3])
print(a[0:])
print(a[:3])
print(a[::-1])

#  slicing in matrix-----------
c=np.array([[5,10,15],[20,25,30]])
print(c[0:2,0:2])
print(c[0,1:2])
print(c[0,1])

# attributes  in numpy--------------
print(np.shape(b))       # gives order of matrix
print(np.size(b))          # gives total number of elemnet
print(np.ndim(b))                # gives dimesninal of matrix
print(b.dtype)        # gives data type



[10 20 30 40 50 60]
<class 'numpy.ndarray'>
[[1 2 3]
 [5 6 7]
 [8 9 6]]
[10 20 30]
[10 20 30 40 50 60]
[10 20 30]
[60 50 40 30 20 10]
[[ 5 10]
 [20 25]]
[10]
10
(3, 3)
9
2
int64


In [1]:
import numpy as np
a=[[10,20,30],[40,50,60]]
print(a)
print(type(a))
a=np.array(a)
print(type(a))
print(a)
print(a.shape)
print(a.size)


print(a.ndim)
print(len(a))
print(type(a))
print(a.dtype)
print(a.astype(float))



[[10, 20, 30], [40, 50, 60]]
<class 'list'>
<class 'numpy.ndarray'>
[[10 20 30]
 [40 50 60]]
(2, 3)
6
2
2
<class 'numpy.ndarray'>
int64
[[10. 20. 30.]
 [40. 50. 60.]]


In [9]:
import numpy as np
a=np.array([[10,20],[30,40]])
b=np.array([[30,20],[10,40]])





print(a+b)
print(np.add(a,b))
print(a-b)
print(np.subtract(a,b))
print(a*b)
print(np.multiply(a,b))
print(a/b)
print(np.divide(a,b))
print(np.sqrt(a))
print(np.power(a,b))


[[40 40]
 [40 80]]
[[40 40]
 [40 80]]
[[-20   0]
 [ 20   0]]
[[-20   0]
 [ 20   0]]
[[ 300  400]
 [ 300 1600]]
[[ 300  400]
 [ 300 1600]]
[[0.33333333 1.        ]
 [3.         1.        ]]
[[0.33333333 1.        ]
 [3.         1.        ]]
[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]
[[ 5076944270305263616 -2101438300051996672]
 [     590490000000000                    0]]


In [11]:
import numpy as np
tbc=[10,20,30,40]
death=[100,50,40,30]
print(np.corrcoef(tbc,death))

[[ 1.         -0.91350028]
 [-0.91350028  1.        ]]
